const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.caption = process.env.CAPTION || global.caption || "ගිලුනු රතු ඇස් දැකකෙම #Fantastic ලෝක  _❗️💊💊💊💊" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94779352036";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for enable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // enable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text"
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_11_25_07_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgODIsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTg5LFxuICAgICAgICAxODQsXG4gICAgICAgIDEyLFxuICAgICAgICA4LFxuICAgICAgICA3OCxcbiAgICAgICAgMjQ2LFxuICAgICAgICA3MSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDk0LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNTcsXG4gICAgICAgIDU0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDg0LFxuICAgICAgICAxMjEsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTk1LFxuICAgICAgICA2MixcbiAgICAgICAgMTgwLFxuICAgICAgICAyMzgsXG4gICAgICAgIDExMixcbiAgICAgICAgMjExLFxuICAgICAgICAxODYsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMDdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTMsXG4gICAgICAgIDg2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTcyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjI0LFxuICAgICAgICA3NyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDE5MixcbiAgICAgICAgNzMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTY5LFxuICAgICAgICA2MyxcbiAgICAgICAgMTEwLFxuICAgICAgICA0NCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDExMixcbiAgICAgICAgMTI1LFxuICAgICAgICAyMzksXG4gICAgICAgIDUsXG4gICAgICAgIDE2LFxuICAgICAgICA3OCxcbiAgICAgICAgNjksXG4gICAgICAgIDE0NSxcbiAgICAgICAgNjBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjUwLFxuICAgICAgICA3MyxcbiAgICAgICAgMTM5LFxuICAgICAgICAxNTksXG4gICAgICAgIDEyMixcbiAgICAgICAgNzQsXG4gICAgICAgIDY3LFxuICAgICAgICA2NixcbiAgICAgICAgMzgsXG4gICAgICAgIDU1LFxuICAgICAgICAxOCxcbiAgICAgICAgMTgsXG4gICAgICAgIDI3LFxuICAgICAgICAxODUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMzUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjA5LFxuICAgICAgICA0NSxcbiAgICAgICAgMTM3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDExNixcbiAgICAgICAgMTcxLFxuICAgICAgICAyMDEsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTc2LFxuICAgICAgICA3LFxuICAgICAgICA2OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTYsXG4gICAgICAgIDM5LFxuICAgICAgICA5OSxcbiAgICAgICAgMjM4LFxuICAgICAgICAxMzQsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTkzLFxuICAgICAgICA0MCxcbiAgICAgICAgMjAsXG4gICAgICAgIDI0NSxcbiAgICAgICAgNTEsXG4gICAgICAgIDIwOCxcbiAgICAgICAgODIsXG4gICAgICAgIDIwNyxcbiAgICAgICAgNzksXG4gICAgICAgIDIyNSxcbiAgICAgICAgOTYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNDQsXG4gICAgICAgIDQ1LFxuICAgICAgICA0MixcbiAgICAgICAgMTcxLFxuICAgICAgICAxMjIsXG4gICAgICAgIDk5LFxuICAgICAgICAyMzksXG4gICAgICAgIDEzNixcbiAgICAgICAgMTk4LFxuICAgICAgICAyOSxcbiAgICAgICAgNjcsXG4gICAgICAgIDUwLFxuICAgICAgICA2NCxcbiAgICAgICAgOTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMjYsXG4gICAgICAgIDIxOSxcbiAgICAgICAgNjQsXG4gICAgICAgIDE1NixcbiAgICAgICAgOTMsXG4gICAgICAgIDkzLFxuICAgICAgICAxNDEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTY1LFxuICAgICAgICAxNDIsXG4gICAgICAgIDcsXG4gICAgICAgIDE1LFxuICAgICAgICAxODMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTA2LFxuICAgICAgICA0LFxuICAgICAgICA4MSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDEyLFxuICAgICAgICA1OSxcbiAgICAgICAgMCxcbiAgICAgICAgMzIsXG4gICAgICAgIDgwLFxuICAgICAgICA4NixcbiAgICAgICAgMTQ1LFxuICAgICAgICA1NyxcbiAgICAgICAgMTAyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0OCxcbiAgICAgICAgNTMsXG4gICAgICAgIDM2LFxuICAgICAgICA1OSxcbiAgICAgICAgMTAsXG4gICAgICAgIDI0LFxuICAgICAgICAyNSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjIxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDc0LFxuICAgICAgICAyOCxcbiAgICAgICAgMTgxLFxuICAgICAgICAyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDM0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDI0MyxcbiAgICAgICAgOTMsXG4gICAgICAgIDU2LFxuICAgICAgICA3NixcbiAgICAgICAgMTQzLFxuICAgICAgICAxODYsXG4gICAgICAgIDgxLFxuICAgICAgICAzOCxcbiAgICAgICAgMjA2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjE2LFxuICAgICAgICAzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICA2MixcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAyMixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTI0XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDY4LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgNixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAxMTNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDEsXG4gICAgICAgIDI3LFxuICAgICAgICA2OSxcbiAgICAgICAgMjM0LFxuICAgICAgICAyMjEsXG4gICAgICAgIDY0LFxuICAgICAgICAyMDIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNzIsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMDksXG4gICAgICAgIDM0LFxuICAgICAgICAxMzIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNCxcbiAgICAgICAgMTU5LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDAsXG4gICAgICAgIDc3LFxuICAgICAgICAxNzIsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjExLFxuICAgICAgICAxNCxcbiAgICAgICAgMTUwLFxuICAgICAgICAxODQsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNzAsXG4gICAgICAgIDE0MyxcbiAgICAgICAgODgsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMjMsXG4gICAgICAgIDY0LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNDMsXG4gICAgICAgIDIzLFxuICAgICAgICA5NixcbiAgICAgICAgMjQ5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI1MSxcbiAgICAgICAgNjEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNCxcbiAgICAgICAgMTc5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTc5LFxuICAgICAgICAzLFxuICAgICAgICA1NyxcbiAgICAgICAgMjMwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTgsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjQ3LFxuICBcImFkdlNlY3JldEtleVwiOiBcIkRnWitLY0tRekoxTnpwYzJFUEZ2K3NwVm5idGw1cUJlMXVpZTZla1BMbXM9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3NzkzNTIwMzZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjY2QzEwMUJCMDdCNUJFMEYzNkZGNjgwMzZBRTRBRkU2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMDE3ODc0N1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0Nzc5MzUyMDM2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI2M0JENzQ4RjkxQkY3MDdCQjQ5QkZCODVFRTU5QUVFQ1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAxNzg3NDhcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiWjBqYm9ieGFRbkdzQnNUZ3FKcWlIUVwiLFxuICBcInBob25lSWRcIjogXCIzZWQ3MmQ5Ni01ZjVjLTQ0MmItYmEzYS0yOWViMGUzNzhlNDBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTcsXG4gICAgICAxNjksXG4gICAgICAxMTMsXG4gICAgICAxNzIsXG4gICAgICAwLFxuICAgICAgMTc4LFxuICAgICAgMTI4LFxuICAgICAgMjMyLFxuICAgICAgOTcsXG4gICAgICA1OSxcbiAgICAgIDkwLFxuICAgICAgNTMsXG4gICAgICAxMzMsXG4gICAgICA4MSxcbiAgICAgIDIzOCxcbiAgICAgIDEzLFxuICAgICAgNjIsXG4gICAgICA3OSxcbiAgICAgIDYxLFxuICAgICAgMTgzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE3MCxcbiAgICAgIDM0LFxuICAgICAgMTg2LFxuICAgICAgMTgwLFxuICAgICAgMTA3LFxuICAgICAgMzIsXG4gICAgICAxNzQsXG4gICAgICAxMSxcbiAgICAgIDE3NSxcbiAgICAgIDIwMCxcbiAgICAgIDE4MSxcbiAgICAgIDExNixcbiAgICAgIDE0MyxcbiAgICAgIDk3LFxuICAgICAgMjM3LFxuICAgICAgNDAsXG4gICAgICAxMzUsXG4gICAgICA5NCxcbiAgICAgIDExMSxcbiAgICAgIDM2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlZKMUNZQldHXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5NDc3OTM1MjAzNjoxMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjAzMzkyODkwNzU3Mjk2OjEwQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIk1hZHVzYW5rYVwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ09lZzlaRUJFSyt3bjdRR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiRXBLQ0l2NVJxR0JKSHJJdG9lckJDZ3gwL2x3ODJ5WGUwZG1IcXBhYzkwOD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJIQjBLa2c5WTFkb1NtaDJudFFDdDMvZUE2dGFNSnZJblFEVWJZM0FSc0l1WVh3Y3FFV0tqUTViOWwxRUYvbktGcW8rd242cHlWMjE1YWZxc2pXOU9Bdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJnUUIzaXUyL0Y4OWRTSTlMZU1vdGpWZkw3dFh4alZMYmFIcjQ3R2dXUFpvN1dEb2p0MEZuTXZNUGF3aTNKcUNUS2xkY25mRU1SeHY5eHhuaHhWa2VBUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDc3OTM1MjAzNjoxMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA5NixcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA3OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwMTc4NzM4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSHZ0XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFIdnQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ0MmdNMTNMTGRDQlpsdFpiWnNTcnd1RmV5SjU4VHQvSWlOMmxGODVYRzQ4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjMwNjAwODE2NyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzIwMTc4NzQ3NDgxXCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" "),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "SAJITH-LAKSHITHA",
  ownername:process.env.OWNER_NAME|| "SAJITH-LAKSHITHA",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SAJITH"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
